chore: check if anvil is available

diff --git a/.github/workflows/github-actions.yml b/.github/workflows/github-actions.yml
--- a/.github/workflows/github-actions.yml
+++ b/.github/workflows/github-actions.yml
@@ -116,6 +116,13 @@ jobs:
           node-version: 22
           cache: "pnpm"
 
+      - name: Check anvil existence
+        run: |
+          if ! command -v anvil &> /dev/null; then
+            echo "anvil could not be found"
+            exit 1
+          fi
+
       - name: Install dependencies
         run: pnpm install --frozen-lockfile
 
